#      ██████╗██╗███╗   ███╗██████╗ ██╗     ███████╗████████╗ █████╗  ██████╗
#     ██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝╚══██╔══╝██╔══██╗██╔════╝
#     ╚█████╗ ██║██╔████╔██║██████╔╝██║     █████╗     ██║   ███████║██║  ██╗
#      ╚═══██╗██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝     ██║   ██╔══██║██║  ╚██╗
#     ██████╔╝██║██║ ╚═╝ ██║██║     ███████╗███████╗   ██║   ██║  ██║╚██████╔╝
#     ╚═════╝ ╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝

# What to do when a player gets tagged
tag-actions:
  - "effect give {player} speed 1000000 3"



# What to do when a player tags someone else
untag-actions:
  - "effect clear {player}"
  - "effect give {player} speed 1000000 2"

virus-mode: false
